package org.sneer.networker;

/*
 * Callbacks generated by a NetworkerDevice implementor.
 */
public interface DeviceListener {
	
	/**
	 * Receive an unreliable, unordered, non-duplicate-protected, non-
	 *   integrity-checked (that is, no typical "guarantee") datagram 
	 *   that just arrived from the overlay/network implemented by the 
	 *   associated Device. Or, more simply, "receive something that went 
	 *   through something like UDP/IP transport."
	 * @param sender Who sent it to us.
	 * @param data What was sent to us.
	 */
	public void receive(NetId sender, byte[] data);
}
